---
extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true
  truthy:
    # Allow 'on'/'off' values (common in config files)
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
